# limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=10r/s;

server {
    listen 80;
    listen [::]:80;
    server_name pensieve.siru.ink;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name pensieve.siru.ink;
    ssl_certificate /etc/ssl/certs/your_ssl_certificate.crt;
    ssl_certificate_key /etc/ssl/private/your_private_key.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;

    location / {
        limit_req zone=ratelimit burst=5 nodelay;
        limit_req_status 429;  # Return 429 Too Many Requests

        include proxy_params;
        proxy_pass http://localhost:8020/;
    }

    access_log off;
    error_log /dev/null;
}
